"""add rules and alerts tables

Revision ID: ca0dced0e6f7
Revises: 
Create Date: 2025-12-20 11:55:55.456098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca0dced0e6f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('device_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('farm_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('zone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_alerts_zone_time'))
        batch_op.create_foreign_key(None, 'devices', ['device_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'farms', ['farm_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'rules', ['rule_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('zone_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_telemetry_device_time'))

    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.alter_column('farm_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.alter_column('farm_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_telemetry_device_time'), ['device_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('zone_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_alerts_zone_time'), ['zone_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.alter_column('zone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('read')
        batch_op.drop_column('severity')
        batch_op.drop_column('farm_id')
        batch_op.drop_column('device_id')
        batch_op.drop_column('rule_id')

    op.drop_table('rules')
    # ### end Alembic commands ###
