# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import telemetry_pb2 as telemetry__pb2


class TelemetryIngestionServiceStub(object):
    """-------------------------------------------------------------
    SERVICES
    -------------------------------------------------------------

    Ingestion Path: Edge Devices/Mock Engines -> Ingestion Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.unary_unary(
                '/telemetry.TelemetryIngestionService/StreamTelemetry',
                request_serializer=telemetry__pb2.TelemetryPacket.SerializeToString,
                response_deserializer=telemetry__pb2.IngestionResponse.FromString,
                )


class TelemetryIngestionServiceServicer(object):
    """-------------------------------------------------------------
    SERVICES
    -------------------------------------------------------------

    Ingestion Path: Edge Devices/Mock Engines -> Ingestion Service
    """

    def StreamTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryIngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=telemetry__pb2.TelemetryPacket.FromString,
                    response_serializer=telemetry__pb2.IngestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.TelemetryIngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TelemetryIngestionService(object):
    """-------------------------------------------------------------
    SERVICES
    -------------------------------------------------------------

    Ingestion Path: Edge Devices/Mock Engines -> Ingestion Service
    """

    @staticmethod
    def StreamTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/telemetry.TelemetryIngestionService/StreamTelemetry',
            telemetry__pb2.TelemetryPacket.SerializeToString,
            telemetry__pb2.IngestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class MockEngineControlServiceStub(object):
    """Control Plane Path: Action Gateway -> Edge Devices/Mock Engines
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCommand = channel.unary_unary(
                '/telemetry.MockEngineControlService/ExecuteCommand',
                request_serializer=telemetry__pb2.GridControlCommand.SerializeToString,
                response_deserializer=telemetry__pb2.CommandAcknowledgement.FromString,
                )


class MockEngineControlServiceServicer(object):
    """Control Plane Path: Action Gateway -> Edge Devices/Mock Engines
    """

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MockEngineControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=telemetry__pb2.GridControlCommand.FromString,
                    response_serializer=telemetry__pb2.CommandAcknowledgement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.MockEngineControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MockEngineControlService(object):
    """Control Plane Path: Action Gateway -> Edge Devices/Mock Engines
    """

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/telemetry.MockEngineControlService/ExecuteCommand',
            telemetry__pb2.GridControlCommand.SerializeToString,
            telemetry__pb2.CommandAcknowledgement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
